### ISSUE TITLE
Problem with regex

### ISSUE THREAD

**Issue by Rolv-Apneseth** [SabrinaJewson/rofi-mode.rs#2]
Hey, just checking out this project as I am trying to turn a small program I made into an actual `rofi` plugin. I'm having this issue with `regex` causing a panic and I was wondering if you have any insights into why it might be happening or if there is anything I can do about it? This is with `RUST_BACKTRACE=1`

```bash
thread '<unnamed>' panicked at 'regex: thread ID allocation space exhausted', /home/rolv/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/regex-1.8.1/src/pool.rs:81:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: std::thread::local::fast::Key<T>::try_initialize
   3: regex::re_unicode::Regex::captures_iter
   4: rofi_games::steam::get_steam_games
   5: <rofi_games::GamesMode as rofi_mode::Mode>::init
   6: std::panicking::try
   7: rofi_mode::init
   8: <unknown>
   9: <unknown>
  10: g_main_context_dispatch
  11: <unknown>
  12: g_main_loop_run
  13: main
  14: <unknown>
  15: __libc_start_main
  16: _start
```

Any help would be appreciated, and if `regex` just doesn't work with this for whatever reason that's fine too, I'll continue on the approach of just launching it as a custom script with `modi`.

**Comment by SabrinaJewson** [comment]
This should be fixed in version 0.3.0 — it was due to out-of-bounds accesses as a result of `rofi-plugin-sys`’ bindings being outdated.

**Comment by SabrinaJewson** [comment]
Thanks for reporting by the way! It took quite a while to track down but I got there in the end

**Comment by Rolv-Apneseth** [comment]
Ah nice, no problem and thanks for fixing it
