### ISSUE TITLE
[REQUEST] Add examples

### ISSUE THREAD

**Issue by Rolv-Apneseth** [SabrinaJewson/rofi-mode.rs#3]
Hey, thanks for making this it's great. After you made that fix for #2, I managed to use this to convert my janky tool to an actual `rofi` plugin so that was cool. I will say, it was a little tough to actually figure out how things were supposed to be used / how they worked, but thanks to the [rofi-vscode-mode](https://github.com/fuljo/rofi-vscode-mode) repo I managed to get it all sorted (as far as I can tell). Icons were particularly difficult as I was using full image paths, and the `file://` would actually make them not work, I guess cause they are not icon files?

Would it be possible to add some examples of usage, maybe just in an `examples` folder, and perhaps slightly more comprehensive documentation for `docs.rs`? I understand if you don't want to spend too much time on this though, maybe I could have a go at making some changes if you wanted.

Regardless, thanks again, great library

**Comment by SabrinaJewson** [comment]
I would very much like to add more examples if you have particular ideäs for some. I was inspired to make the [file-browser](https://github.com/SabrinaJewson/rofi-mode.rs/tree/main/examples/file-browser) example after seeïng this issue, which you might find helpful. Really the only limitation is I’m not sure what else to write, haha.

Re the `file://` thing, I tested it and it seems like you can just pass in unprefixed image paths and it works just fine. I only wrote in the stuff about the `file://` prefix because that’s what Rofi’s documentation says, but I guess that’s wrong.

And with `docs.rs`, what kind of stuff would you like to see in the docs? I think I’m somewhat blinded by writing the library myself, so I’m not sure what parts need clarification.

**Comment by Rolv-Apneseth** [comment]
That example is perfect, and I will be honest, I did not see that basic example before, guess I am blind. Both would have helped tremendously, and removed any of my confusion with the docs. Guess I need to improve my Rust, but I got caught up on some very basic stuff like where do I use the `'rofi`, as the readme was using `'_`, and how do I access a specific entry so I can define the behaviour for each of the `entry_` functions (maybe `line` could be renamed `entry_index` or similar, though that is up to you). 

Anyway I believe with those 2 examples there should be no problems for new users, thanks.

> Re the `file://` thing, I tested it and it seems like you can just pass in unprefixed image paths and it works just fine. I only wrote in the stuff about the `file://` prefix because that’s what Rofi’s documentation says, but I guess that’s wrong.

Yeah I found this when I was exploring the option of making it a custom script rather than a full mode, not sure why it says that.

---

As a side note, how would you feel about adding some shields to the readme, such as version, crates.io version and licence? Maybe also changing the description to match the about's `High-level Rust library for creating Rofi plugins and custom modes`, as currently it's repeating the title

**Comment by SabrinaJewson** [comment]
I’ve updated the docs now to make them hopefully a bit more clear about the `line` parameters; I also added links in the README to the examples so people can’t miss in future.

---

Shields would be cool — just make sure it’s kept in sync with the docs in `src/lib.rs` (IIRC I use [cargo-readme](https://github.com/livioribeiro/cargo-readme) for this)

**Comment by Rolv-Apneseth** [comment]
> I’ve updated the docs now to make them hopefully a bit more clear about the `line` parameters; I also added links in the README to the examples so people can’t miss in future.

Cool thank you

> Shields would be cool — just make sure it’s kept in sync with the docs in `src/lib.rs` (IIRC I use [cargo-readme](https://github.com/livioribeiro/cargo-readme) for this)

That's a cool program. Could I add a `README.tpl` file to adjust it so that it could go title > badges > readme as the default has the badges above. Also were you ok with that change to the description / first line of the readme?

**Comment by Rolv-Apneseth** [comment]
I'm actually having a bit of trouble with that tool, there aren't many badges available and it appears to be unmaintained (last update 3 years ago from what I can see). Can I output the text from it but then add badges to the readme manually?

Edit: It appears [this](https://github.com/orium/cargo-rdme) is a more updated tool for the same thing? Although again it has the badges above the title, I suppose it would be personal preference but I think it looks a lot better under the title.

Edit2: Alright my bad didn't investigate that other tool enough, it appears the heading is defined separately in that one so having the badges under works. I'll make changes with that tool in mind if that's alright
