### ISSUE TITLE
[Q/A]: updating entries dynamically?

### ISSUE THREAD

**Issue by atahabaki** [SabrinaJewson/rofi-mode.rs#7]
I just have a simple, may be dumb question:

Can I update entries dynamically? Let's say I'm scanning the filesystem for changes, when it happens, the entries are changing. Can I do that?

Couldn't figured out how to trigger Reload event.

**Comment by SabrinaJewson** [comment]
I don’t believe Rofi offers a way to do this — you just have to rely on `entries`, `entries_content` & co being called often enough.

**Comment by atahabaki** [comment]
I don't have knowledge about ffi bindings but rofi has a function called: `rofi_view_reload()`, i get that from [here](https://github.com/davatorium/rofi/discussions/1654). I have assumed that the rofi actually can do that.

**Comment by SabrinaJewson** [comment]
Ah, you’re right that it exists. It’s an undocumented API, which is why I wasn’t aware of it.

The comment next to it has this warning “This can only be done when *more* information is available” — it’s not clear whether this means it can invoke UB or not. So for now, with not an ideä of how to make it safe, I added a binding to the function to [`rofi_plugin_sys`](https://docs.rs/rofi-plugin-sys) and you can call it unsafely via `rofi_plugin_sys::view::reload()`. PRs welcome if you have good reason to believe it can be exposed in a safe way!

**Comment by atahabaki** [comment]
Thanks, helped a lot. :+1:  Although it didn't work. I suppose, I'm going to quit using rofi then. It does not offer me a way to run async tasks. I'm waiting to see the list of Access Points. Can't place a Spinner/LoadingBar/Anything that serves users to wait a bit while functions happening. I quit. Thanks for your efforts & help, that saved me time. Or I'm dumb that I can not even write an async/multithreaded application.

May force be with you!

**Comment by zspher** [comment]
here is a plugin that does async loading: https://git.sr.ht/~qball/rofi-ntfy. 

if I am not mistaken, to translate what rofi-ntfy does to something in rofi-mode.rs, 
1. `fn init(api: rofi_mode::Api<'rofi>) -> Result<Self, ()>` needs to have access to self -> fn `init(&mut self, api: rofi_mode::Api<'rofi>) -> Result<Self, ()>` or a new function is added with the express purpose dealing with dynamic content
2. `rofi_plugin_sys::view::reload()` needs to be called when the data is updated
3. some process is split and has access to and can change the current mode private data

so far as a hacky solution, I have used `react`, `preprocess_input` and `message` to change the data, but this is not dynamic and updates only happen when a user inputs text or some `Event` is called.


<details>
<summary>example hacky solution</summary>

```rust
    fn react(&mut self, event: Event, input: &mut rofi_mode::String) -> rofi_mode::Action {
        unsafe {
            ffi::view::reload();
        }
        match event {
            Event::Ok {
                alt: true,
                selected: _,
            } => {
                if input.contains("nap") {
                    self.entries[0] = "nap".to_string();
                }
                return rofi_mode::Action::Reload;
            }
            Event::Ok {
                alt: false,
                selected: _,
            } => {
                return rofi_mode::Action::Exit;
            }
            _ => (),
        }

        rofi_mode::Action::Reload
    }
```
</details>
