### ISSUE TITLE
Potential problem with rofi dependency upgrade

### ISSUE THREAD

**Issue by Rolv-Apneseth** [SabrinaJewson/rofi-mode.rs#8]
Hey Sabrina, I've run into a potential problem, which is also present in a couple other rofi plugins. Basically the mode is not being detected on a specific branch of rofi, but this might just be because it has changes not yet in the current release of `rofi`.

So I this first came to my attention with a random update to a package I use, basically a `rofi` branch specifically for wayland, found on the AUR with its repo [here](https://github.com/lbonn/rofi). I dismissed it as a bug with this version since using regular `rofi` caused no issues. But someone else [opened an issue](https://github.com/Rolv-Apneseth/rofi-games/issues/7) on my repo so I dug into it a little bit more. 

I found that this problem was also present on [rofi-calc](https://github.com/svenstaro/rofi-calc) and [rofi-emoji](https://github.com/Mange/rofi-emoji) since I have those installed and the same warning came up for them:

```
(process:395587): Rofi-WARNING **: 15:04:25.265: ABI version of plugin: 'calc.so' does not match: 00000006 expecting: 00000007

(process:395587): Rofi-WARNING **: 15:04:25.265: ABI version of plugin: 'games.so' does not match: 00000006 expecting: 00000007

(process:395587): Rofi-WARNING **: 15:04:25.266: ABI version of plugin: 'emoji.so' does not match: 00000006 expecting: 00000007
```

I looked through their issues, and while there were issues listed on both, there was a very helpful one on `rofi-emoji`, [here](https://github.com/Mange/rofi-emoji/issues/65), which suggests this is an issue with a `rofi` dependency upgrade. The referenced PR there might be helpful. The changes seem minimal but the owner of the repo points out that support for both the old version and the new one may be required.

Sorry I can't be of more help, but what do you think? Is this something you would be willing to look into?

**Comment by SabrinaJewson** [comment]
I don’t believe it’s possible for a single plugin `.so` to support multiple versions of rofi — the way plugins work is that each `.so` exports a /single/ item with a fixed, static ABI version number. We could add functionality to rofi-mode.rs that enables support of multiple versions — i.e. the user of this library would pick which version of Rofi they wish to support — or we could cut our losses and only support the new version.

Upgrading would involve figuring out what ABI changes have actually been made, then changing first `rofi-plugin-sys` and then `rofi-mode`. I won’t be able to get to this in the next few days at least, so PRs welcome in the meantime.

**Comment by Rolv-Apneseth** [comment]
Ah, tough one. I guess just supporting the new version would be easiest.

I understand you're busy so the following is just for whenever you have the time:

Just to be clear I have very little understanding of how this all works, but I was having a go at making this work with the updated version (just launching `rofi-games` to test it). I was trying to set the mode type like the PR for that `rofi-emoji` issue did but it seemed to make no difference. Simply changing the `ABI_VERSION` from 6 to 7 in `rofi-plugin-sys` makes it at least launch-able, though I then run into a new issue. When using icons, CPU usage spikes, icons don't appear and the following warning message is printed repeatedly:

```bash
(process:203960): Helpers.IconFetcher-WARNING **: 23:14:53.930: Querying an non-existing uid
```

This is with icons only, no icons seems to work no problem. Is it still related or would you say that's a separate issue due to the new version specified? I see you have other potential issues listed with the unreleased `rofi` version [here](https://github.com/SabrinaJewson/rofi-plugin-sys.rs/issues/2), could it be one of those? The first one seems a likely culprit but I have no idea how to even begin solving the issue.

**Comment by SabrinaJewson** [comment]
ABI issues manifest in very weird ways, so I would hazard a guess that it’s _probably_ the ABI mismatch issue causing it.

> The first one seems a likely culprit but I have no idea how to even begin solving the issue.

You would have to observe all the changes made to the Rofi header files (e.g. see how [mode.rs](https://github.com/SabrinaJewson/rofi-plugin-sys.rs/blob/main/src/mode.rs) references Rofi’s `include/mode.h`), and make sure that the Rust type signatures used in `rofi-plugin-sys` match it. Then you can just fix the type errors as they show up in `rofi-mode`.

**Comment by Rolv-Apneseth** [comment]
I've tried my best but I've hit a block, because I really don't know what changes to make to `rofi-mode.rs` for things to work. You mentioned type errors showing up in `rofi-mode` but I haven't seen any, guess it's different kind of changes. I believe I got the changes made to `rofi-plugin-sys.rs` but of course the issue could very well still be coming from there.

I'm no longer getting the previous warnings and am now getting these:

```bash
(process:204431): GdkPixbuf-CRITICAL **: 23:17:52.460: gdk_pixbuf_new_from_file_at_scale: assertion 'width > 0 || width == -1' failed

(process:204431): GLib-GObject-CRITICAL **: 23:17:52.460: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

Icons still aren't displayed but no slow down happens anymore. I've noticed the mode name doesn't seem appear either.

I may have to leave this to you for whenever you have some time to work on this, unless you want to give me some more tips on how I should proceed. I just feel bad asking for so much hand holding. Should I make a PR just so you can see what changes I did try making to `rofi-plugin-sys.rs`?

**Comment by SabrinaJewson** [comment]
Ah… well thanks for trying. I think it would be easiëst if I do this, I’ll probably have time sometime next week. Sorry it’s been quite delayed.

**Comment by Rolv-Apneseth** [comment]
No worries and no rush. Sorry I couldn't do more. Did you want to see the changes for `rofi-plugin-sys.rs` or you'll just start from scratch?

**Comment by SabrinaJewson** [comment]
Yeah, you might as well post them somewhere.

**Comment by SabrinaJewson** [comment]
@Rolv-Apneseth Try running `cargo update` to update to `rofi-plugin-sys` 0.3.2, then building with `RUSTFLAGS="--cfg rofi_next"`. The examples in this repo work for me that way (if I use Rofi’s latest commit).

**Comment by Rolv-Apneseth** [comment]
Awesome, thank you. It does run with no errors, but are the icons showing up for you? The 2 examples don't have icons but I tried my plugin and [rofi-vscode-mode](https://github.com/fuljo/rofi-vscode-mode) and they didn't seem to work.

**Comment by SabrinaJewson** [comment]
Both examples have icons (the basic example just loads a computer icon for every entry, and the filebrowser example loads icons for all image files) and it worked for me 🤔 

I also tested with a different program that loads icons from images and it seemed to work.

**Comment by SabrinaJewson** [comment]
The icons also work fine with your rofi-vscode-mode plugin for me. I cloned your repo and ran:

```
cargo update
export RUSTFLAGS="--cfg rofi_next"
cargo build --release --lib --features rofi
ROFI_PLUGIN_PATH=target/release /path/to/my/build/of/rofi -modi vscode-recent -show vscode-recent
```

**Comment by Rolv-Apneseth** [comment]
Oh it's not mine, just a different plugin that also uses your library. My one is [rofi-games](https://github.com/Rolv-Apneseth/rofi-games). Weird, must be the `rofi` fork I'm using, [rofi-lbonn-wayland-git](https://github.com/lbonn/rofi) from the AUR.

If they work alright on the regular updated `rofi` for you though then it's fine. The fork is 10 commits behind so that might well be it. **EDIT** Wow sorry I didn't actually look at the commits ahead but it does seem to touch pretty much everything. No wonder there are problems.

Just to leave these for reference, here are the errors showing up for me (which look like the same I had before when I was making my attempt):

```bash
(process:34098): GdkPixbuf-CRITICAL **: 21:51:08.852: gdk_pixbuf_new_from_file_at_scale: assertion 'width > 0 || width == -1' failed

(process:34098): GLib-GObject-CRITICAL **: 21:51:08.852: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by Rolv-Apneseth** [comment]
Oh wow, thank you for opening that issue

**Comment by SabrinaJewson** [comment]
@Rolv-Apneseth Now that https://github.com/lbonn/rofi/pull/102 is merged, can you try it again?

**Comment by Rolv-Apneseth** [comment]
Yeah all working now. Thank you!

**Comment by SabrinaJewson** [comment]
Nice!
